ALTER SESSION SET CONTAINER = ORCLCDB;
ALTER SESSION SET CURRENT_SCHEMA = sys;

CREATE TABLE ACCOUNTS (
  ACCOUNT_NUMBER VARCHAR2(15) PRIMARY KEY,
  msisdn VARCHAR2(11) NOT NULL,
  status VARCHAR2(10)
);
