ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO sus CONTAINER=CURRENT;
GRANT CREATE SESSION TO sus CONTAINER=CURRENT;
GRANT RESOURCE TO sus CONTAINER=CURRENT;

ALTER USER sus QUOTA 100M ON USERS;
