ALTER SESSION SET CONTAINER = ORCLPDB1;
ALTER SESSION SET CURRENT_SCHEMA = sus;

CREATE TABLE ACCOUNTS (
  ACCOUNT_NUMBER VARCHAR2(15) PRIMARY KEY,
  msisdn VARCHAR2(11) NOT NULL,
  status VARCHAR2(10)
);

INSERT INTO ACCOUNTS
VALUES(1,'Hi','ok');
